set_property IOSTANDARD LVCMOS33 [get_ports {digits[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
set_property PACKAGE_PIN W4 [get_ports {digits[3]}]
set_property PACKAGE_PIN V4 [get_ports {digits[2]}]
set_property PACKAGE_PIN U4 [get_ports {digits[1]}]
set_property PACKAGE_PIN U2 [get_ports {digits[0]}]
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]
set_property PACKAGE_PIN W7 [get_ports {segments[6]}]
set_property PACKAGE_PIN W6 [get_ports {segments[5]}]
set_property PACKAGE_PIN U8 [get_ports {segments[4]}]
set_property PACKAGE_PIN V8 [get_ports {segments[3]}]
set_property PACKAGE_PIN U5 [get_ports {segments[2]}]
set_property PACKAGE_PIN V5 [get_ports {segments[1]}]
set_property PACKAGE_PIN U7 [get_ports {segments[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports btn_center]
set_property IOSTANDARD LVCMOS33 [get_ports btn_left]
set_property IOSTANDARD LVCMOS33 [get_ports btn_down]
set_property IOSTANDARD LVCMOS33 [get_ports btn_right]
set_property IOSTANDARD LVCMOS33 [get_ports btn_up]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports btn_up]
set_property PACKAGE_PIN T17 [get_ports btn_right]
set_property PACKAGE_PIN W19 [get_ports btn_left]
set_property PACKAGE_PIN U17 [get_ports btn_down]
set_property PACKAGE_PIN U18 [get_ports btn_center]

# Clock signal
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]	

#USB HID (PS/2)
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]						
	set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
	set_property PULLUP true [get_ports PS2_CLK]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]					
	set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]	
	set_property PULLUP true [get_ports PS2_DATA]